spring.application.name=Airline
server.port=8082

# POSTGRESQL CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/airline_db
spring.datasource.username=reis
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

jwtSecreteString=airline123456789airline123456789airline123456789

#Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=de.burakyilmaz@gmail.com
spring.mail.password=hotd wbin dkur zkfl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

frontendLoginUrl=http://localhost:3000/login
viewBookingUrl=http://localhost:3000/my-bookings